[package]
name = "fontobene_webeditor"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
debug = true
